#JLopez-20251013: Yaml files documentation: https://learnxinyminutes.com/yaml/
# This is a basic workflow to help you get started with Actions
name: simple-ci-linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "current" branch
  push:
    branches: [ "current" ]
  pull_request:
    branches: [ "current" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      - name: copy files to the CI folder
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
